### ISSUE TITLE
How to find same project, different CDN, different "name" field?

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/api#10]
How can I find just the Ember CDN, if:
```
http://api.jsdelivr.com/v1/cdnjs/libraries?name=lodash*&fields=name
[{"name": "lodash.js"}]
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=lodash*&fields=name
[{"name": "lodash"}]
http://api.jsdelivr.com/v1/cdnjs/libraries?name=ember*&fields=name
[{"name":"ember-data-django-rest-adapter"},{"name":"ember-data.js"},{"name":"ember-resource.js"},{"name":"ember.js"}]
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=ember*&fields=name
[{"name":"ember.localstorage-adapter"},{"name":"ember.table"},{"name":"emberjs"}]
```
There are other mismatched project names: `underscore.js`|`underscorejs`, `can.js`|`canjs`, hard to say how many now or in future.  Not sure of the best approach?
* client-side or server-side lookup table (might grow large)
* switching to RegEx, since I can't figure out how to use [minimatch](https://github.com/isaacs/minimatch#features) here.  In RegEx, I think all of the above files would be isolated via `NAME.?(js)?`, right?

thanks :)

**Comment by megawac** [comment]
Related to #78 /cc @tomByrer

**Comment by jimaek** [comment]
https://github.com/jsdelivr/api/issues/78
