### ISSUE TITLE
API returns no versions (urgent)

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#106]
https://api.jsdelivr.com/v1/jsdelivr/libraries?name=css3-metro-buttons
`"versions": [ ],`

@UnbounDev @megawac

**Comment by megawac** [comment]
Is that with or without my changes? Is
https://github.com/jsdelivr/api/pull/105 still on the server?

Regardless, it works locally on api-sync (haven't tested on api)

**Comment by jimaek** [comment]
Currently I have `master` deployed. So all of your changes included

**Comment by megawac** [comment]
@jimaek this ((https://github.com/jsdelivr/api/pull/105) needs to be reverted. It removes all versions which are semver incompatible. api issue not api-sync

**Comment by tomByrer** [comment]
Reverting for now works, but I was thinking as a longer term solution to recast non-SemVer into compliant SemVer.
What do you think?

**Comment by jimaek** [comment]
This is a long term solution.  megawac applied a fix to api-sync https://github.com/jsdelivr/api-sync/commit/1ab5e8227d6ad43cac4db9120760627da2e4bc1c
