### ISSUE TITLE
Move the API away from AppFog

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#108]
They are closing their current service and forcing everyone to move to the new one. Its more expensive and lacks the CI support the v1 has.
Got to find alternatives.

**Comment by tomByrer** [comment]
Docker container, Node hosting, or "I don't care, just get it hosted!"?

**Comment by jimaek** [comment]
Yeah, I think I will end up using Docker on my own server

**Comment by UnbounDev** [comment]
Props if you can couple that deployment w/ a test `api#v2` application on the same box (it'd be nice to move away from appfog completely).

**Comment by jimaek** [comment]
I was thinking we could use the free Heroku dyno for testing stuff. What do you think?

**Comment by jimaek** [comment]
Done. The API is now hosted in a Docker container on my server. All commits into master are automatically deployed to production.

**Comment by UnbounDev** [comment]
> free Heroku dyno for testing stuff

As long as we can set up autodeploy, free and testing go together well!

**Comment by jimaek** [comment]
the v2 branch is now auto-deployed to https://jsdelivr-api.herokuapp.com/ (if Travis passes)

**Comment by tomByrer** [comment]
:+1:
