### ISSUE TITLE
Am I right to assume that I cannot get data for multiple librarys with one api call?

### ISSUE THREAD

**Issue by nextgenthemes** [jsdelivr/api#109]
`http://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery&fields=mainfile,name` fields works with comma.

`http://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery,bootstrap&fields=mainfile,name` however, this fails.

or can I do it differently without getting all the libs at once? If not that may be a idea for v2

**Comment by jimaek** [comment]
Yes you cant do that with v1, but its a great idea for v2.

**Comment by jimaek** [comment]
This is now present in v2 beta

**Comment by tomByrer** [comment]
I'm guessing v2 is not live yet?

**Comment by jimaek** [comment]
Its not. You can test it here https://jsdelivr-api.herokuapp.com/v2/jsdelivr/libraries
