### ISSUE TITLE
jQuery failed to update latest beta1

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/api#112]
http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery  Missing v 3.0.0 beta.
[Affecting website](https://github.com/jsdelivr/www.jsdelivr.com/issues/69)?

**Comment by jimaek** [comment]
Cant say why it happened but after a restart it was fixed. If it happens again I will look into it in more detail

**Comment by tomByrer** [comment]
"Unplug & replug the machine" is a common fix action ;)  v2.2.0 is listed now also BTW.
cheers
