### ISSUE TITLE
Incorrect author format for some CDNJS projects

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/api#118]
E.g. [jquery](http://api.jsdelivr.com/v1/cdnjs/libraries/jquery). Some other projects [are OK](http://api.jsdelivr.com/v1/cdnjs/libraries/twitter-bootstrap). @jimaek this should probably be fixed in v1 as well?

**Comment by jimaek** [comment]
Lets leave v1 as is. How do you plan to fix http://api.jsdelivr.com/v1/cdnjs/libraries/jquery in v2?
What format would `author` have in this case?

**Comment by MartinKolarik** [comment]
I'd take the `name` property, so in this case `jQuery Foundation and other contributors`. If there's no `name`, it can be empty, but it certainly shouldn't be an object when it's supposed to be a string.

**Comment by jimaek** [comment]
Ok, then lets do that. String in v2, dont change v1
