### ISSUE TITLE
pagination need?

### ISSUE THREAD

**Issue by bimohxh** [jsdelivr/api#126]
If  pagination is needed to speed the API request ?maybe some time I just need request 10 data but you give me 1000 data

**Comment by jimaek** [comment]
What exactly are you trying to do? Give me some examples

**Comment by awesomes-cn** [comment]
Just get the data I need,  reduce the response data size and  save  the request time

**Comment by gavinhungry** [comment]
@jimaek,

I think what @bimohxh wants to do is limit the number of results in a query. For example, searching for `jquery*` yields an unwieldy number of results:
https://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery*

There used to be a `limit` query parameter that could be used for this purpose:
https://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery*&limit=10

However, I think that was a feature of `rest-sugar`, which this API no longer relies on, so the feature was lost.
