### ISSUE TITLE
The result order is not right

### ISSUE THREAD

**Issue by bimohxh** [jsdelivr/api#127]
please visit http://api.jsdelivr.com/v1/jsdelivr/libraries?name=bootstrap*&fields=mainfile,name,versions

I just want to search `bootstrap` but it not be placed at first.

**Comment by gavinhungry** [comment]
I solved this problem with a merged pull request 2 years ago:
962c228737ea3b542f8851d30cbe20980c3be877

However, it was removed here (/cc @UnbounDev):
0b70303ada984f957f37537ec7aa7bbce26cce42

Clearly, I should have included a test in my PR.

**Comment by MartinKolarik** [comment]
This is fixed/changed in v2. Probably not something we want to change in v1 now.

**Comment by gavinhungry** [comment]
Really? It was already in v1 (for about a year). I'm assuming that it was only removed by accident.
