### ISSUE TITLE
Default filename for specified version

### ISSUE THREAD

**Issue by staskjs** [jsdelivr/api#128]
I am writing a vim plugin that will automatically insert a link to specified js library into html. I am using your API for that and I have figured out how to get mainfile for latest version of a library, but I haven't succeed in getting mainfile for a particular version.

http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery?fields=mainfile - this returns me mainfile, like I wanted
but http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery/2.0.3?fields=mainfile - returns list of files. 

How do I get default filename for specified version?

**Comment by jimaek** [comment]
@MartinKolarik Any ideas? What can we do about this?
Do you have support for mainfiles per version in v2?

**Comment by MartinKolarik** [comment]
IIRC this should work in v2.

@jimaek any idea what might be wrong with https://jsdelivr-api.herokuapp.com/v2/jsdelivr/libraries ?

**Comment by jimaek** [comment]
Not sure. Just re-deployed and its still broken. The only change was the move of the api-sync server. But I changed the IP in the config and v1 works just fine

**Comment by MartinKolarik** [comment]
@jimaek weird. Is the port also correct?

@staskjs there's no support for that in v1, I'm afraid. In v2, the `assets` list will look like this:

```
  "assets": {
    "1.10.1": {
      "baseUrl": "https://cdn.jsdelivr.net/jquery/1.10.1/",
      "files": [
        "jquery.min.js",
        "jquery-1.10.1.min.map",
        "jquery.js",
        "jquery.min.map"
      ],
      "mainfile": "jquery.min.js"
    },
    "1.10.2": {
      "baseUrl": "https://cdn.jsdelivr.net/jquery/1.10.2/",
      "files": [
        "jquery-1.10.2.min.js",
        "jquery-1.10.2.min.map",
        "jquery-1.10.2.js",
        "jquery.js",
        "jquery.min.js",
        "jquery.min.map"
      ],
      "mainfile": "jquery.min.js"
    }
  }
```

**Comment by jimaek** [comment]
@staskjs The v2 demo is online now https://jsdelivr-api.herokuapp.com/v2/jsdelivr/library/jquery
Will that work?

**Comment by staskjs** [comment]
@jimaek I think it will, thank you!

**Comment by jimaek** [comment]
Please dont use the demo URL in production. We will try to push v2 live as soon as we can.

**Comment by amgadfahmi** [comment]
any update on this! got an experimental [lib ](https://github.com/amgadfahmi/scripty) using ur APIs
