### ISSUE TITLE
Add `normname` field

### ISSUE THREAD

**Issue by bebraw** [jsdelivr/api#13]
Now it's very difficult to find the same library across different CDNs. In order to solve this I propose adding `normname` (stands for normalized name) field. For GitHub projects, it's <author>/<project>. If GitHub link is not available, project name is used instead.

**Comment by jimaek** [comment]
Closing because I dont see a good solution to this problem that will work with every single project we host (and others host)

**Comment by tomByrer** [comment]
I don't see why an automated script could not pick a name out of a tiered prioritized list of sources?  A few (1%?) could need human interaction, but some of jsdelivr/jsdelivr needs human interaction anyhow.
