### ISSUE TITLE
API future

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#134]
I suggest freezing the API's DB and deprecating it. With our new backend it no longer serves a purpose.

**Comment by thclev** [comment]
Which new backend is this in reference to? Is there a transition guide?

**Comment by jimaek** [comment]
https://github.com/jsdelivr/jsdelivr/blob/master/beta-readme.md

We are still in progress of updating everything.

**Comment by thclev** [comment]
API usage is as follows: static site generator, get latest version and list of versions along with main css file. Is there an alternative for this? Unfortunately the main file always only lists the js file in a bundle and never the css.
