### ISSUE TITLE
Add a download/hit count to the API

### ISSUE THREAD

**Issue by styfle** [jsdelivr/api#138]
The only way I know of getting this info is from the badge:

https://data.jsdelivr.com/v1/package/npm/marked/badge

However the badge is already rounded and doesn't give options of per day/week/month.

1. Is there a way to read the download/hit count stats from the API?
2. How do you differentiate between npm hits vs github hits?

I tried this url but no luck to answer either of my questions: https://api.jsdelivr.com/v1/jsdelivr/libraries?name=marked

**Comment by MartinKolarik** [comment]
Wrong repo 😄 This is an old version of the API. I think you'll find the answer to both questions in the README of the new API: https://github.com/jsdelivr/data.jsdelivr.com#get-package-usage-stats

**Comment by MartinKolarik** [comment]
Also the badges support day/week/month/year values: https://github.com/jsdelivr/data.jsdelivr.com#get-a-badge-for-your-project

**Comment by styfle** [comment]
Oops, I searched "api" and this was the first hit with a description "Looking for contributors - API for public CDNs" so I got confused 😅  https://github.com/jsdelivr?utf8=✓&q=api

Maybe you should archive this repo? https://help.github.com/articles/archiving-a-github-repository/

I think you answered my questions 😄 
I'll move the conversation to https://github.com/jsdelivr/data.jsdelivr.com/issues/5

**Comment by MartinKolarik** [comment]
@jimaek let's do that.

**Comment by jimaek** [comment]
Not sure if that is correct since its technically still online and working for legacy users.  What if we need to migrate it to some other hosting provider and have to commit changes. Will the provider even see the repo if its archived?

**Comment by MartinKolarik** [comment]
Alternatively change the description to "DEPRECATED - API for public CDNs"

**Comment by jimaek** [comment]
added
