### ISSUE TITLE
API endpoint down?

### ISSUE THREAD

**Issue by MickeyKay** [jsdelivr/api#139]
Hi there 👋🏼. I built a WordPress plugin which hits http://api.jsdelivr.com/v1/jsdelivr/libraries/fontawesome/?fields=versions,lastversion to grab version data for a hosted resource, and it looks like suddenly api.jsdelivr.com is no longer working. Is this a known issue? I can work to update to the newer api (data.), however based on the read me I would have expected things to keep working for the time being:
> All endpoints will continue to work. . .

Can I expect this to be repaired, or is this endpoint now down permanently? If so, was there a reason it was taken down today? Thanks all!

**Comment by jimaek** [comment]
Hey, it looks like Stackpath unexpectedly and without notice just stopped sponsoring us and deactivated our account which resulted in downtime of everything we had there. The main CDN was not impacted but the old API was :(
We were expecting this and had migrated most things but we also expect to get some kind of notice which would allow us to finish migrating the final pieces.

I have now removed them and changed our DNS so api.jsdelivr.com should start working really soon.

But also please note that we deprecated this API 5 years ago. Ideally you should switch to the new API over here https://github.com/jsdelivr/data.jsdelivr.com

**Comment by szepeviktor** [comment]
> But also please note that we deprecated this API 5 years ago.

It would be nice to migrate from that API in the WordPress plugin.
https://github.com/MickeyKay/better-font-awesome/issues/27
