### ISSUE TITLE
Add `/libraries`

### ISSUE THREAD

**Issue by bebraw** [jsdelivr/api#16]
It would be potentially interesting to add a library oriented resource. Example:

**GET `/v2/libraries?normname=jquery/jquery`** (need to use a normalized name here to avoid name clashes (just see all color libs))

```json
[
    {
        "normname": "jquery/jquery",
        "_id": "ey8mGL8Bp7q",
        "created": "2014-02-25T08:48:09.270Z",
        "description": "jQuery is a fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development. jQuery is designed to change the way that you write JavaScript.",
        "homepage": "http://jquery.com/",
        "github": "https://github.com/jquery/jquery",
        "author": "jQuery Foundation",
        "cdns": {
            "jsdelivr": {
                "name": "jquery",
                "mainfile": "jquery.min.js",
                "zip": "jquery.zip",
                "lastversion": "2.1.0",
                "versions": [
                    "2.1.0",
                    "2.0.3",
                    "2.0.2",
                    "2.0.1",
                    "2.0.0",
                    "1.11.0",
                    "1.10.2",
                    "1.10.1",
                    "1.10.0",
                    "1.9.1",
                    "1.9.0",
                    "1.8.3",
                    "1.7",
                    "1.4.4"
                ],
                "assets": [
                    {
                        "version": "2.1.0",
                        "files": [
                            "jquery.js",
                            "jquery.min.js",
                            "jquery.min.map"
                        ]
                    },
                    ...
                ]
            },
            "cdnjs": {...},
            "google": {...}
        }
    }
]
```

This simply aggregates the current information in a different format. In the beginning you can see common meta (name, description etc.). CDN specific information is stored to `cdns`.

Possible additional benefit of the scheme is that it would allow us to aggregate libraries not available in any CDNs yet to the index.

**Comment by jimaek** [comment]
Due to lack of bulletproof normalized names I think we can close this issue as its very hard to do.

**Comment by megawac** [comment]
Do you think this cannot be done *well enough* through some hybrid matching:

```
jquery.x ~~ jquery-x ~~ jquery+x
```

**Comment by jimaek** [comment]
yes, we have some pretty big differences in some projects. Some are hosted only on a single CDN as well. I dont see a solution to every single problem we would have

**Comment by tomByrer** [comment]
> Do you think this cannot be done well enough through some hybrid matching:

Or just use all the names in all available CDNs (array)?  Might make some projects easier to find.

**Comment by jimaek** [comment]
What you say sounds more like a `/search` endpoint that allows the search through all the CDNs we have. But it wont work for the main endpoint to get a project's info.
