### ISSUE TITLE
requests for .map throws 404 if the original library is in a grouped request

### ISSUE THREAD

**Issue by ryanpitts** [jsdelivr/api#27]
We just discovered this because Underscore is one of the libraries we use. If I request Underscore on its own, like so:

`<script src="//cdn.jsdelivr.net/underscorejs/1.6.0/underscore-min.js"></script>`

Then Chrome dev tools sees that there's a .map file, and requests it automatically from:

`//cdn.jsdelivr.net/underscorejs/1.6.0/underscore-min.map`

However, if we include Underscore in a grouped request:

`<script src="//cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4,typeahead.js@0.10,underscorejs@1.6,spinjs@1.3,handlebarsjs@1.3(handlebars.min.js)"></script>`

Chrome attempts to find the .map file in the same directory, which in this case will 404:

`//cdn.jsdelivr.net/g/underscore-min.map`

This doesn't break the public-facing site, of course, so it's not a critical issue. I'm not sure what the best way to fix it would be. The Underscore javascript includes a line like:

`//# sourceMappingURL=underscore-min.map`

Which is obviously telling dev tools where to go looking for the .map file. Not sure if it's easiest to change that, or to add some logic to the /g/ grouping somehow.

**Comment by brgrz** [comment]
Still an issue with this
https://github.com/jsdelivr/jsdelivr/issues/3814
