### ISSUE TITLE
Prune `/libraries` out of urls?

### ISSUE THREAD

**Issue by bebraw** [jsdelivr/api#28]
I wonder if we should just drop `libraries` from url. That's the only resource type we serve so now it seems redundant. We could do this change in `v2`.

**Comment by UnbounDev** [comment]
Given #62, we're now planning to serve more than just the `libraries` resource (e.g. `/jsdelivr/analytics`) - can we close this issue?

**Comment by jimaek** [comment]
Yes, I think it makes sense. Our API got bigger
