### ISSUE TITLE
Confirm recency

### ISSUE THREAD

**Issue by fulldecent** [jsdelivr/api#47]
The index file `http://api.jsdelivr.com/v1/jsdelivr/` shows all included CDNs.

I would like to ask that here or some other location will explicitly state that date the the data files were last updated.

**Comment by jimaek** [comment]
@UnbounDev Can we add this data? How often do we purge the CDN? If this data stays cached then it will be useless and no point adding it in the first place

**Comment by UnbounDev** [comment]
The lokijs db we're using includes a `meta` field, e.g.
```
// http://api.jsdelivr.com/v1/jsDelivr/libraries/imagesloaded
// =>
{
...,
"meta": {
  "revision": 35,
  "created": 1433183937543,
  "version": 0,
  "updated": 1433204947949
},
"$loki": 465
}
```

where `created`/`updated` are timestamps relating to when that particular project was initalized/updated w/i the api - is that sufficient or is it desirable to have a 'master' meta file?

**Comment by jimaek** [comment]
Yes but how often do we purge the CDN cache?

**Comment by UnbounDev** [comment]
@jimaek after each sync cycle (~10 minutes)

**Comment by jimaek** [comment]
Hmm then I guess this issue is fixed. @UnbounDev Can you note somewhere to make sure we document this feature?
