### ISSUE TITLE
Cannot GET /v1/jquery/libraries

### ISSUE THREAD

**Issue by fulldecent** [jsdelivr/api#53]
![screen shot 2014-08-31 at 9 15 49 pm](https://cloud.githubusercontent.com/assets/382183/4103806/85665cc6-3175-11e4-8f50-544e2e389425.png)

**Comment by hubdotcom** [comment]
Either remove this reference from Readme.MD or enable it? https://github.com/jsdelivr/api-sync/blob/master/config/config.template.js
