### ISSUE TITLE
Bootstrap API down

### ISSUE THREAD

**Issue by markcarver** [jsdelivr/api#58]
https://api.jsdelivr.com/v1/bootstrap/libraries returns:
```Cannot GET /v1/bootstrap/libraries```

**Comment by UnbounDev** [comment]
Thanks for the report, we're looking into a fix for this now.

**Comment by UnbounDev** [comment]
@markcarver there was an error regarding rate-limiting on the service that refreshes the status of the jsdelivr api db for bootstrap, we've fixed that and are working to ensure the error is handled appropriately in the future.

**Comment by markcarver** [comment]
Awesome :) Thanks for such an amazing API! I maintain the [Drupal Bootstrap base-theme](https://www.drupal.org/project/bootstrap) and, even though I have a fail-safe in place in case it goes down, I got a ping over in the #drupal-bootstrap IRC channel on freenode that it was down.

FWIW, this explains how the base-theme uses the API https://www.drupal.org/node/2452617

**Comment by UnbounDev** [comment]
That's seriously cool! You'll be happy to learn that the fix we've just pushed includes significant enhancements to the stability of bootstrap library hosting, cheers - and thanks for using jsdelivr :)
