### ISSUE TITLE
Add Pingdom data

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#60]
I want to create a special endpoint that will serve uptime data per provider.
The data will be pulled from Pingdom's API every 4 minutes.
We need to extract the status of each provider and format it in a way Cedexis can eat it. (Example Fusion apps http://developers.cedexis.com/)

The point is to add an additional monitoring level to jsDelivr.
Our load balancing will use these endpoints to pull data every 5 minutes and will use it to remove providers if Pingdom detects downtime.

An example:

api.jsdelivr.com/v1/uptime/pingdom/CloudFlare
api.jsdelivr.com/v1/uptime/pingdom/MaxCDN
...

We also need a way to configure which tests to pull from Pingdom.

**Comment by jimaek** [comment]
@UnbounDev Please have this task in mind when rebuilding api-sync. Same goes for https://github.com/jsdelivr/api/issues/62

**Comment by jimaek** [comment]
Btw this endpoint is going to be used inside `cdn.jsdelivr.net` which means that it has the power to impact the whole service. Thats why we need to make sure it works and serves the latest possible data without running into rate-limits.

**Comment by UnbounDev** [comment]
@jimaek do you have any examples of the Pingdom api endpoints we'd want to use for this? Also, there are a lot of applications listed on http://developers.cedexis.com - which one am I looking for as a reference to desired format?

**Comment by jimaek** [comment]
>examples of the Pingdom api endpoints 

Not sure what you mean.

Here are some examples using Fusion.
https://github.com/cedexis/openmixapplib/blob/master/apps-javascript/load-external-config/app.js
https://github.com/cedexis/openmixapplib/blob/master/apps-javascript/ortt%2Bfusion-health/app.js
https://github.com/cedexis/openmixapplib/blob/master/apps-javascript/fusion-custom-get-json/app.js

**Comment by UnbounDev** [comment]
Sorry - I meant do you know which Pingdom api endpoints to hit for that data (before I go digging through their docs)?

**Comment by jimaek** [comment]
Should be this one https://www.pingdom.com/features/api/documentation/#ResourceChecks

**Comment by tomByrer** [comment]
Would it be better to have a different app/server, to make things easier to develop & uptime?
The URL can be redirected, I'm just thinking there should be a separate repo (jsdelivr/api-pingdom) & Docker image.

**Comment by jimaek** [comment]
An other App to monitor and debug... I think its simple enough to get this data into our existing API.

**Comment by jimaek** [comment]
@UnbounDev or @megawac Can we start this? A simple json as output is enough, we can parse it out on the Cedexis side. The important is to have live data without hitting Pingdom limits.

```
GET api.jsdelivr.com/v2/uptime/pingdom/MaxCDN

{
status: "up" //or "down"
}

```

**Comment by jimaek** [comment]
Btw its only for v2

**Comment by UnbounDev** [comment]
@jimaek we're close to being able to start this task; the physical code would go inside of the tasks/sync portion of the API, that code is currently being worked on for the new sync process - after we deploy that code to production (along w/ the corresponding api-sync code) we should be able to tweak the tasks to accommodate this feature.

**Comment by jimaek** [comment]
Cedexis Fusion will be pulling our API every minute. This means that every time they pull we need to have a new live value from Pingdom. 
Format:

```
GET api.jsdelivr.com/v2/uptime/pingdom/CloudFlare

[
    {
        "health": "5"
    }
]


```

5 = online
0 = down


### Question
Should we pull the uptime info ourselves from Pingdom or use their webhook functionality? https://support.pingdom.com/Knowledgebase/Article/View/94/0/users-and-alerting-end-points

**Comment by megawac** [comment]
I'd say webhook, but either is fine

**Comment by jimaek** [comment]
Note to self: Make sure we dont cache these values on the CDN.
