### ISSUE TITLE
Issue with CORS support

### ISSUE THREAD

**Issue by thekondrashov** [jsdelivr/api#67]
The response of any requests to public api doesn't contain any CORS headers, including this important header:
```http
Access-Control-Allow-Origin: *
```
You can check this with the developer tools in your browser or [here](http://tools.pingdom.com/fpt/#!/eQDczd/https://api.jsdelivr.com/v1/jsdelivr/libraries) (from Pingdom).
Without this header, it is impossible to make CORS requests.

**Comment by jimaek** [comment]
@thekondrashov This should be fixed, can you try again please?

**Comment by thekondrashov** [comment]
Yes, now it works fine. Thank you.
Could you also add support JSON-P callbacks like [Github API](https://developer.github.com/v3/#json-p-callbacks)?
> This is typically used when browsers want to embed content in web pages by getting around cross domain issues. (Github API docs)

It will be very cool:
```
> https://api.jsdelivr.com/v1/jsdelivr/libraries?callback=foo

/**/foo({
  "meta": {
    "status": 200
  },
  "data": {
    // the data
  }
})
```

**Comment by jimaek** [comment]
@UnbounDev Does it make sense to add this feature? What do you think?

**Comment by UnbounDev** [comment]
I don't see why not, express makes this ridiculously [easy](http://expressjs.com/api.html#res.jsonp). I've added issue #77 for this.

**Comment by jimaek** [comment]
Great, im closing this then.

**Comment by thekondrashov** [comment]
Thanks
