### ISSUE TITLE
API v2 Feedback/Ideas

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#71]
We are actively working on v2 of our API and since most of you are using or have used our API in the past I wanted to listen to your ideas and feedback that you might have.  [This is what we have so far](https://github.com/jsdelivr/api/issues?q=is%3Aopen+is%3Aissue+label%3Av2)

Let me know what changes you would like to see to make v2 even better and more powerful.

@MickeyKay @bebraw @gavinhungry @markcarver @fulldecent @GeorgeErickson @ryanpitts @vvo

**Comment by bebraw** [comment]
You can get Dotcom monitor data easily through the interface we implemented for cdnperf. Here are the [API docs](http://wiki.dotcom-monitor.com/programming-interfaces/using-the-xml-reporting-service-xrs/). So it's just a matter of parsing that and mapping to an endpoint. Maybe start with Pingdom first since there's a nice client available and you can get more data through it.

**Comment by jimaek** [comment]
@bebraw We only need the uptime data from Pingdom, not the performance. So there is no need to combine multiple tools. Pingdom should be reliable enough to detect downtime across all of our CDNs.

**Comment by bebraw** [comment]
Ok, Pingdom is more accurate for uptime anyhow.

**Comment by jimaek** [comment]
@bebraw Anything we can add/change to improve our integration with osscdn.com?

**Comment by bebraw** [comment]
@jimaek I can see one thing - pagination (old API **might** have it, not sure). If you have that, you can do dynamic loading on scroll etc. A good feature to have anyhow.

It might go beyond the scope of the API but you could consider setting up a service to get screenshots for libraries and so on. That'll help to improve the outlook somewhat.

**Comment by tomByrer** [comment]
I'm mostly focused on finding a project on [multiple CDNs](https://github.com/jsdelivr/api/issues/16) in a single API call.  This could also allow all the CDN sources give the same output.
