### ISSUE TITLE
Remove useless fields

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#74]
```
"zip": "",
"mainfile2": "",
```
These can die in peace.

Also do we need `"$loki": 858` ?

**Comment by tomByrer** [comment]
https://github.com/jsdelivr/api/issues/33#issuecomment-41080955 ?
And having a 2nd field for the many JS+CSS projects (eg Bootstrap) would be useful.

**Comment by jimaek** [comment]
mainfile2 was a test but got replaced by the mainfile per version which is live to this day.

**Comment by tomByrer** [comment]
Ah, sure let them go, unless you want to give a new purpose to use
`mainfile2` mean a second main (eg CSS).

**Comment by UnbounDev** [comment]
@jimaek we could shape the responses s.t. there is no `$loki` (it is used internally to identify the object w/i the lokijs db); however, this would require creating an object that has all elements **except** `$loki` - that's not so bad for calls that request a single library but can be murder when a user requests all libraries w/i the api.
