### ISSUE TITLE
CDNjs improvements

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#75]
http://api.jsdelivr.com/v1/cdnjs/libraries?name=jquery

1. `author": null,`
2. Each file has a `size` parameter. Do we need it? I think we can remove it and save the resources
3. `github` is empty but I think we can populate it

Any other improvements we can do?

**Comment by UnbounDev** [comment]
1. 3. : if these can be solved (I believe they can) it is an api-sync issue.
2. Nope, I kept it around b/c it was present in the previous response from the cdnjs api - we can toss it but that will effect api v1 as well (b/c we would be dropping this from api-sync).

**Comment by jimaek** [comment]
Ok. I think we can toss it from v1 as well.

**Comment by UnbounDev** [comment]
@jimaek this is fixed via an api-sync enhancement.

http://api.jsdelivr.com/v1/cdnjs/libraries?name=jquery
