### ISSUE TITLE
Add support for jsonp callbacks

### ISSUE THREAD

**Issue by UnbounDev** [jsdelivr/api#77]
Use the express `res.jsonp()` response type to allow jsonp callbacks.

See #67 for background info.

**Comment by jimaek** [comment]
@UnbounDev Btw all the v2 tagged issues should mostly be applied to v2 and not v1. If you are unsure about one then ask me. For example we should not add jsonp to v1.

**Comment by UnbounDev** [comment]
Sounds good!
