### ISSUE TITLE
Closest matching

### ISSUE THREAD

**Issue by megawac** [jsdelivr/api#78]
A query endpoint to find the closest match would be extremely convenient (current use case is duckduckgo spice answers).

What this would involve is determining the library that matches a query as close as possible (e.g. `jwuery` may match `jquery` if `jwuery` is not a library). Another thing this should support is searching for plugins

```
/search?name=jquery carousel => jquery.carousel
/search?name=jquery-carousel => jquery.carousel
``` 

There should be an arbitrary threshold to cut off in accurate matches based on levenshtein scores. I'd say `Math.min(query.length / 2, 4)`

Imagining the endpoint would be

```
http://api.jsdelivr.com/v2/jsdelivr/find?name={lib}
```

I'm imagining this returning a single result

**Comment by jimaek** [comment]
What would be the response? Just the correct project name to further query using `http://api.jsdelivr.com/v2/jsdelivr/{correctName}`?

**Comment by megawac** [comment]
Yep, that's what I'm imagining

**Comment by jimaek** [comment]
What if multiple projects match the request? Do we return all of them? Just the first one? How to prioritize?

**Comment by megawac** [comment]
I think it should always return the closest match and one of them as this already exists
```
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=*jq*
```

**Comment by jimaek** [comment]
`http://api.jsdelivr.com/v1/jsdelivr/libraries?name=*jq*`
Returns like 15 projects with full data :)

Your solution is going to return only 1 and only the name?
Like this?
```
{

    "name": "jquery.validation.unobtrusive"
}
END
```

**Comment by megawac** [comment]
I was thinking with full data (for the DDG use case)

**Comment by jimaek** [comment]
If its going to return full data then maybe it makes no sense to use a separate endpoint?
This way it would be cleaner `http://api.jsdelivr.com/v2/jsdelivr/{searchQuery}`

**Comment by megawac** [comment]
`http://api.jsdelivr.com/v2/jsdelivr/{searchQuery}` or `http://api.jsdelivr.com/v2/jsdelivr/name={query}`
?

**Comment by jimaek** [comment]
Its the same thing I believe https://db.tt/QqVwFcmA

**Comment by megawac** [comment]
K but this is a different endpoint

**Comment by jimaek** [comment]
Ok, then I guess `http://api.jsdelivr.com/v2/jsdelivr/name={query}` makes more sense. What do you think?

**Comment by megawac** [comment]
Agreed!
