### ISSUE TITLE
Match versions by ~semvish compatibility

### ISSUE THREAD

**Issue by megawac** [jsdelivr/api#84]
I'd like to see versions matched by `semvish` compatibility rather than regex. For example

```
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=jq*&lastversion=~0.1
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery&lastversion=^1.2
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery&lastversion=1.x
```

I'd also like to see `lastversion` -> `version`

Related to https://github.com/jimaek/jsdelivr-g/issues/2

**Comment by megawac** [comment]
@jimaek thoughts? Should this supercede #39 or is that issue better

**Comment by jimaek** [comment]
I believe `semvish` is more powerful so this issue is looking better. Do you agree?

**Comment by megawac** [comment]
Definetely agree, I would like to drop most of the minimatch stuff in `v2` for more modern approaches.

However, if this goes in I think `jsdelivr-g` will also need a similar change

**Comment by jimaek** [comment]
I dont have plans to change the logic of `jsdelivr-g` in the near feature unfortunately. Do you want to add it only to the API?

**Comment by megawac** [comment]
Working towards this with https://github.com/megawac/SemVish/commit/a02cf2378c662bfbce34e1c77c78a5559ff815da

**Comment by MartinKolarik** [comment]
I started working on this, but after finding out semvish can't handle all version formats, I don't think this is a good idea. We'd have to exclude those projects/versions from all `lastversion` searches.

**Comment by jimaek** [comment]
I dont think that semvish is that important. If its too hard then lets skip this

**Comment by MartinKolarik** [comment]
:+1:
