### ISSUE TITLE
Drop assets from /libraries

### ISSUE THREAD

**Issue by megawac** [jsdelivr/api#88]
Related to adding the `/library` route

Proposition

- Purpose of `/library/*`: determine everything about a library that matches the query, including
   - name
   - description
   - versions
   - meta
   - assets
- Purpose of `/libraries/*`: get a summary of all libraries that matches the query, including
   - name
   - description
   - versions
   - meta

This should make `/libraries` responses significantly smaller but require people to make two queries if they want more information about a lib

/cc @jimaek @tomByrer  @UnbounDev

**Comment by jimaek** [comment]
As long as we make our documentation super clear then I support this. Otherwise we will need assets in /libraries to point to /library

**Comment by tomByrer** [comment]
> make our documentation super clear

Sorry, I don't know what `meta` is.

Is `/library` a single exact search, or best fuzzy search?

Could `/libraries/*` search across all CDNs?  Thanks to the smaller subset of returned data, don't have to worry about merging data.

**Comment by UnbounDev** [comment]
> Sorry, I don't know what meta is.

`meta` contains information on when the applications records were created and updated (relative to an individual library w/i a CDN); e.g.

```
"meta": {
      "revision": 14,
      "created": 1433305097630,
      "version": 0,
      "updated": 1433314711229
}
```

We get this object for free from the internal lokijs db.

**Comment by tomByrer** [comment]
Ah, data about the record(s).  Thanks I understand now.
