### ISSUE TITLE
"bootstrap" alias is gone in v1

### ISSUE THREAD

**Issue by markcarver** [jsdelivr/api#94]
I think this is related to the work in #69, but basically the folder alias that BootstrapCDN has is no longer in v1 of the API: http://api.jsdelivr.com/v1/bootstrap/libraries?name=bootstrap.

I understand this change is likely needed/wanted, but it should only have affected v2. This is technically a regression for v1 as it has affected [existing code](http://cgit.drupalcode.org/bootstrap/tree/includes/cdn.inc?id=85682c7ecdee68e16b17b8da387e9848676d51b8#n164) that relies on this alias provided in v1.

x-ref: https://www.drupal.org/node/2504343

**Comment by markcarver** [comment]
x-ref: https://github.com/MaxCDN/bootstrap-cdn/blob/develop/public/bootstrap

**Comment by UnbounDev** [comment]
@markcarver thanks this is an oversite on my part  - I'll have a fix up momentarily

**Comment by UnbounDev** [comment]
@markcarver the fix is deploying now - turns out the original `twitter-bootstrap` library was being aliased to `bootstrap` under the old sync structure, it didn't fit well, the patch I've just submitted should be through shortly.

**Comment by markcarver** [comment]
Awesome :) Thanks for the quick turn around! Can I assume that in v2 this alias will be gone?

**Comment by UnbounDev** [comment]
It's up! http://api.jsdelivr.com/v1/bootstrap/libraries?name=bootstrap (you may need to hit the refresh button) - no worries, sorry about the mixup.

That's a question for @jimaek, I'm okay w/ keeping it but I'd like to do so w/ proper code on the api-sync side (the little hack I just patched isn't the cleanest :)

**Comment by markcarver** [comment]
Fair enough. I have already gone and [patched Drupal Bootstrap](http://cgit.drupalcode.org/bootstrap/commit/?id=a2e9cd1) to use the real library name `twitter-bootstrap`  (just in case it does).

**Comment by jimaek** [comment]
@markcarver Sorry for this issue, I hope it didnt severely impact your app. I will make sure this wont happen again

@UnbounDev No need for hacks in `v2` its not backwards compatible. Lets make it clean and fast. Also be careful with v1, we cant break anything.
