### ISSUE TITLE
Make sure logentries is utilized

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#99]
Log what is needed to debuging and remove what is not needed.

@megawac @UnbounDev  You both have access to our Logentries account, check out jsDelivr API host and what it currently logs. I want to make sure our logs are useful

**Comment by UnbounDev** [comment]
@megawac - I've previous 'logentrieified' `api-sync` and have a wrapper built there, I'll optimize/integrate that code w/ `api` if you don't mind.

**Comment by megawac** [comment]
Go for it
